# Yarn v2+ configuration
# Auto-select versions and use resolutions
nodeLinker: node-modules
enableGlobalCache: true
enableTelemetry: false
preferInteractive: false
defaultSemverRangePrefix: "^"

# Use package.json resolutions for version conflicts
enableResolutions: true
