#!/bin/bash
# Generated cleanup script
echo "🧹 Starting project cleanup..."
# SAFE MODE: Files will be moved to .cleanup-backup/
mkdir -p .cleanup-backup
mv "lighthouse-test.mjs" .cleanup-backup/ 2>/dev/null || echo "Could not move lighthouse-test.mjs"
mv "payment-test.html" .cleanup-backup/ 2>/dev/null || echo "Could not move payment-test.html"
mv "public/debug-daily.html" .cleanup-backup/ 2>/dev/null || echo "Could not move public/debug-daily.html"
mv "public/debug.html" .cleanup-backup/ 2>/dev/null || echo "Could not move public/debug.html"
mv "scripts/quick-test-payment-links.sh" .cleanup-backup/ 2>/dev/null || echo "Could not move scripts/quick-test-payment-links.sh"
mv "src/services/__tests__/DailyChallengeService.test.ts" .cleanup-backup/ 2>/dev/null || echo "Could not move src/services/__tests__/DailyChallengeService.test.ts"
mv "test-analytics.ts" .cleanup-backup/ 2>/dev/null || echo "Could not move test-analytics.ts"
mv "test-daily-challenge.js" .cleanup-backup/ 2>/dev/null || echo "Could not move test-daily-challenge.js"
mv "test-daily-challenge.mjs" .cleanup-backup/ 2>/dev/null || echo "Could not move test-daily-challenge.mjs"
mv "test-react.js" .cleanup-backup/ 2>/dev/null || echo "Could not move test-react.js"
mv "test-results.json" .cleanup-backup/ 2>/dev/null || echo "Could not move test-results.json"
mv "tests/comprehensive-use-cases.spec.ts" .cleanup-backup/ 2>/dev/null || echo "Could not move tests/comprehensive-use-cases.spec.ts"
mv "tests/difficulty-distribution-test.ts" .cleanup-backup/ 2>/dev/null || echo "Could not move tests/difficulty-distribution-test.ts"
mv "tests/purchase-flows.spec.ts" .cleanup-backup/ 2>/dev/null || echo "Could not move tests/purchase-flows.spec.ts"
mv "tests/utils/cross-browser-helpers.ts" .cleanup-backup/ 2>/dev/null || echo "Could not move tests/utils/cross-browser-helpers.ts"
mv "vitest.config.ts" .cleanup-backup/ 2>/dev/null || echo "Could not move vitest.config.ts"
mv "src/components/EyeOfRa.tsx" .cleanup-backup/ 2>/dev/null || echo "Could not move src/components/EyeOfRa.tsx"
mv "src/config/firebase-clean.ts" .cleanup-backup/ 2>/dev/null || echo "Could not move src/config/firebase-clean.ts"
mv "src/config/firebase.development.ts" .cleanup-backup/ 2>/dev/null || echo "Could not move src/config/firebase.development.ts"
mv "src/config/live-payment-links.ts" .cleanup-backup/ 2>/dev/null || echo "Could not move src/config/live-payment-links.ts"
mv "src/data/bundles-backup.ts" .cleanup-backup/ 2>/dev/null || echo "Could not move src/data/bundles-backup.ts"
mv "src/screens/AchievementsScreenNew.tsx" .cleanup-backup/ 2>/dev/null || echo "Could not move src/screens/AchievementsScreenNew.tsx"
mv "src/screens/SubscriptionScreen.tsx" .cleanup-backup/ 2>/dev/null || echo "Could not move src/screens/SubscriptionScreen.tsx"
mv "src/types/global.d.ts" .cleanup-backup/ 2>/dev/null || echo "Could not move src/types/global.d.ts"
mv "src/types/stripe.d.ts" .cleanup-backup/ 2>/dev/null || echo "Could not move src/types/stripe.d.ts"
mv "src/utils/firestoreWrapper.ts" .cleanup-backup/ 2>/dev/null || echo "Could not move src/utils/firestoreWrapper.ts"
mv "src/vite-env.d.ts" .cleanup-backup/ 2>/dev/null || echo "Could not move src/vite-env.d.ts"
mv "..bfg-report/2025-07-11/15-43-06/object-id-map.old-new.txt" .cleanup-backup/ 2>/dev/null || echo "Could not move ..bfg-report/2025-07-11/15-43-06/object-id-map.old-new.txt"
mv ".env.example" .cleanup-backup/ 2>/dev/null || echo "Could not move .env.example"
mv ".env.production.example" .cleanup-backup/ 2>/dev/null || echo "Could not move .env.production.example"
mv ".env.supabase.example" .cleanup-backup/ 2>/dev/null || echo "Could not move .env.supabase.example"
mv ".env.template" .cleanup-backup/ 2>/dev/null || echo "Could not move .env.template"
mv ".github/PULL_REQUEST_TEMPLATE/pull_request_template.md" .cleanup-backup/ 2>/dev/null || echo "Could not move .github/PULL_REQUEST_TEMPLATE/pull_request_template.md"
mv ".github/workflows/template-health.yml" .cleanup-backup/ 2>/dev/null || echo "Could not move .github/workflows/template-health.yml"
mv "docs/COMPREHENSIVE_PROJECT_DOCUMENTATION.md" .cleanup-backup/ 2>/dev/null || echo "Could not move docs/COMPREHENSIVE_PROJECT_DOCUMENTATION.md"
mv "docs/CONTRIBUTING.md" .cleanup-backup/ 2>/dev/null || echo "Could not move docs/CONTRIBUTING.md"
mv "docs/GETTING_STARTED.md" .cleanup-backup/ 2>/dev/null || echo "Could not move docs/GETTING_STARTED.md"
mv "docs/MARKETING_STRATEGY.md" .cleanup-backup/ 2>/dev/null || echo "Could not move docs/MARKETING_STRATEGY.md"
mv "docs/MILESTONE_BACKUP_README.md" .cleanup-backup/ 2>/dev/null || echo "Could not move docs/MILESTONE_BACKUP_README.md"
mv "docs/MILESTONE_WORKING_STATE.md" .cleanup-backup/ 2>/dev/null || echo "Could not move docs/MILESTONE_WORKING_STATE.md"
mv "docs/REFERENCES.md" .cleanup-backup/ 2>/dev/null || echo "Could not move docs/REFERENCES.md"
mv "docs/SECURITY.md" .cleanup-backup/ 2>/dev/null || echo "Could not move docs/SECURITY.md"
mv "docs/TEMPLATE_README.md" .cleanup-backup/ 2>/dev/null || echo "Could not move docs/TEMPLATE_README.md"
mv "docs/TESTING_GUIDE.md" .cleanup-backup/ 2>/dev/null || echo "Could not move docs/TESTING_GUIDE.md"
mv "docs/ZERO-COST-MARKETING-STRATEGY.md" .cleanup-backup/ 2>/dev/null || echo "Could not move docs/ZERO-COST-MARKETING-STRATEGY.md"
mv "src/config/live-payment-links.ts.backup" .cleanup-backup/ 2>/dev/null || echo "Could not move src/config/live-payment-links.ts.backup"
echo "✅ Cleanup complete!"