#!/bin/bash

# Authentication System Demo Script
# Ancient History Trivia PWA

echo "🏛️  Ancient History Trivia PWA - Authentication Demo"
echo "================================================="
echo ""

echo "🚀 Starting development server..."
cd "/Users/ronratzlaff/_Dev_Projects/Git Projects/PWA/ancient-history-pwa"

# Check if server is already running
if lsof -Pi :3000 -sTCP:LISTEN -t >/dev/null ; then
    echo "✅ Server is already running on http://localhost:3000"
else
    echo "Starting development server..."
    yarn dev &
    sleep 5
    echo "✅ Server started on http://localhost:3000"
fi

echo ""
echo "🔐 Authentication Features Available:"
echo "=================================="
echo ""
echo "1. 📱 Multi-Provider Sign-In:"
echo "   • Google OAuth"
echo "   • Facebook OAuth" 
echo "   • Apple OAuth"
echo "   • Email/Password"
echo "   • Anonymous/Guest Mode"
echo ""
echo "2. 💳 Subscription Tiers:"
echo "   • 🌟 Explorer (Free) - 3 bundles, 10 questions/day"
echo "   • 📚 Scholar ($4.99/mo) - All bundles, unlimited questions"
echo "   • 🏛️ Historian ($8.99/mo) - Premium + expert content"
echo "   • 👑 Academy ($79.99 lifetime) - All features + institutional tools"
echo ""
echo "3. 👤 User Profile Management:"
echo "   • Profile editing and avatars"
echo "   • Progress tracking"
echo "   • Subscription management"
echo "   • Account preferences"
echo ""
echo "🌐 Demo Instructions:"
echo "==================="
echo ""
echo "1. Open browser to: http://localhost:3000"
echo "2. Click 'Sign In' or 'Sign Up' in the top-right corner"
echo "3. Try different authentication methods:"
echo "   • Google: Simulated OAuth flow"
echo "   • Facebook: Mock social login"
echo "   • Email: Create test account (test@example.com)"
echo "   • Guest: Continue without account"
echo ""
echo "4. After signing in:"
echo "   • Notice personalized greeting on homepage"
echo "   • Click your avatar to view profile"
echo "   • Visit /subscription to see pricing tiers"
echo "   • Try upgrading to different subscription levels"
echo ""
echo "5. Test Features by Subscription:"
echo "   • Free: Limited to 3 bundles"
echo "   • Scholar: All bundles unlocked"
echo "   • Historian: Premium content access"
echo "   • Academy: Institutional features"
echo ""
echo "🔧 Development Notes:"
echo "==================="
echo ""
echo "• Currently using MockAuthContext for demo purposes"
echo "• All authentication is simulated (no real OAuth)"
echo "• User data stored in localStorage"
echo "• Ready for Firebase integration in production"
echo ""
echo "📁 Key Files:"
echo "============"
echo ""
echo "Authentication:"
echo "• src/context/MockAuthContext.tsx - Demo auth system"
echo "• src/context/AuthContext.tsx - Production Firebase auth"
echo "• src/components/AuthModal.tsx - Login/signup UI"
echo ""
echo "Subscription:"
echo "• src/screens/SubscriptionScreen.tsx - Pricing & plans"
echo "• src/data/pricing.ts - Subscription configuration"
echo "• src/screens/UserProfileScreen.tsx - Profile management"
echo ""
echo "🎯 Test Scenarios:"
echo "================="
echo ""
echo "1. New User Flow:"
echo "   → Land on homepage"
echo "   → Click 'Sign Up'"
echo "   → Choose authentication method"
echo "   → See personalized content"
echo "   → Explore subscription options"
echo ""
echo "2. Returning User:"
echo "   → Automatic login (localStorage)"
echo "   → Personalized greeting"
echo "   → Access to purchased content"
echo "   → Profile management"
echo ""
echo "3. Subscription Management:"
echo "   → Compare pricing tiers"
echo "   → Simulate subscription upgrade"
echo "   → Access tier-specific features"
echo "   → View subscription status"
echo ""
echo "✨ Demo is ready! Open http://localhost:3000 to explore the authentication system."
echo ""
