// Stripe Hosted Checkout Configuration
// Auto-generated by create-stripe-prices-and-links.sh

export const STRIPE_PAYMENT_LINKS = {
  // Subscription Plans - FIXED WITH CORRECT PRICING
  monthly: 'https://buy.stripe.com/test_3cIdR884J7b31xz36x9oc0t', // $4.99/month
  annual: 'https://buy.stripe.com/test_cNi3cudp39jb901fTj9oc0u', // $39.99/year
  
  // Individual Bundles - Updated to match actual bundle IDs
  bundles: {
    // Region Packs
    region_pack_egypt: 'https://buy.stripe.com/test_28E4gy3Otdzrfop5eF9oc09',
    region_pack_rome: 'https://buy.stripe.com/test_3cI5kC3Ot8f7ccdePf9oc0a',
    region_pack_greece: 'https://buy.stripe.com/test_dRm8wO2Kp1QJ0tv6iJ9oc0b',
    region_pack_mesopotamia: 'https://buy.stripe.com/test_3cI4gyacRdzrb8922t9oc0c',
    region_pack_china: 'https://buy.stripe.com/test_6oU00ickZgLD6RT9uV9oc0d',
    region_pack_india: 'https://buy.stripe.com/test_28E4gy3Otdzrfop5eF9oc09', // Reuse Egypt link for now
    region_pack_americas: 'https://buy.stripe.com/test_3cI5kC3Ot8f7ccdePf9oc0a', // Reuse Rome link for now
    region_pack_europe: 'https://buy.stripe.com/test_dRm8wO2Kp1QJ0tv6iJ9oc0b', // Reuse Greece link for now
    
    // Difficulty Packs
    difficulty_pack_easy: 'https://buy.stripe.com/test_28E4gy3Otdzrfop5eF9oc09', // Reuse Egypt link for now
    difficulty_pack_medium: 'https://buy.stripe.com/test_3cI5kC3Ot8f7ccdePf9oc0a', // Reuse Rome link for now
    difficulty_pack_hard: 'https://buy.stripe.com/test_dRm8wO2Kp1QJ0tv6iJ9oc0b', // Reuse Greece link for now
    
    // Age Packs
    age_pack_bronze_age: 'https://buy.stripe.com/test_3cI4gyacRdzrb8922t9oc0c', // Reuse Mesopotamia link for now
    age_pack_iron_age: 'https://buy.stripe.com/test_6oU00ickZgLD6RT9uV9oc0d', // Reuse China link for now
    age_pack_prehistoric: 'https://buy.stripe.com/test_28E4gy3Otdzrfop5eF9oc09', // Reuse Egypt link for now
    
    // Format Packs
    format_pack_multiple_choice: 'https://buy.stripe.com/test_3cI5kC3Ot8f7ccdePf9oc0a', // Reuse Rome link for now
    format_pack_true_false: 'https://buy.stripe.com/test_dRm8wO2Kp1QJ0tv6iJ9oc0b', // Reuse Greece link for now
    format_pack_fill_blank: 'https://buy.stripe.com/test_3cI4gyacRdzrb8922t9oc0c' // Reuse Mesopotamia link for now
  }
};

// Pricing information for display - CORRECTED TO MATCH APP PRICING
export const PRICING = {
  monthly: {
    price: 4.99,
    currency: 'USD',
    interval: 'month',
    description: 'Unlock all quiz bundles and premium features'
  },
  annual: {
    price: 39.99,
    currency: 'USD',
    interval: 'year',
    description: 'Unlock all quiz bundles and premium features - Save 33%!'
  },
  biennial: {
    price: 69.99,
    currency: 'USD',
    interval: '2 years',
    description: 'Unlock all quiz bundles and premium features - Save 42%!'
  },
  bundles: {
    egypt: { price: 2.99, currency: 'USD', name: 'Ancient Egypt Bundle' },
    rome: { price: 2.99, currency: 'USD', name: 'Roman Empire Bundle' },
    greece: { price: 2.99, currency: 'USD', name: 'Ancient Greece Bundle' },
    mesopotamia: { price: 2.99, currency: 'USD', name: 'Mesopotamia Bundle' },
    china: { price: 2.99, currency: 'USD', name: 'Ancient China Bundle' }
  }
};

// Redirect to Stripe Checkout - REQUIRES AUTHENTICATION
export const redirectToStripeCheckout = (plan: string) => {
  // CRITICAL: Ensure user is authenticated before allowing Stripe checkout
  const userId = localStorage.getItem('userId');
  if (!userId || userId === 'anonymous') {
    console.error('User must be authenticated before accessing Stripe checkout');
    throw new Error('Authentication required for purchase');
  }
  
  let link: string | undefined;
  
  if (plan === 'monthly' || plan === 'annual') {
    link = STRIPE_PAYMENT_LINKS[plan];
  } else if (plan in STRIPE_PAYMENT_LINKS.bundles) {
    link = STRIPE_PAYMENT_LINKS.bundles[plan as keyof typeof STRIPE_PAYMENT_LINKS.bundles];
  }
  
  if (link) {
    // Add authenticated user ID to the checkout URL for tracking
    const urlWithParams = `${link}?client_reference_id=${userId}`;
    console.log('Redirecting authenticated user to Stripe checkout:', { plan, userId });
    window.location.href = urlWithParams;
  } else {
    console.error('Payment link not configured for plan:', plan);
    alert('Payment link not configured. Please contact support.');
  }
};

// Check if payment links are configured
export const arePaymentLinksConfigured = (): boolean => {
  return STRIPE_PAYMENT_LINKS.monthly.startsWith('https://buy.stripe.com/');
};

// Customer Portal URL (to be configured after setting up Stripe Customer Portal)
export const CUSTOMER_PORTAL_URL = 'https://billing.stripe.com/p/login/YOUR_PORTAL_LINK';

// Open customer portal for subscription management
export const openCustomerPortal = () => {
  if (CUSTOMER_PORTAL_URL !== 'https://billing.stripe.com/p/login/YOUR_PORTAL_LINK') {
    window.open(CUSTOMER_PORTAL_URL, '_blank');
  } else {
    alert('Customer portal not configured yet. Please contact support.');
  }
};

// Track subscription events for analytics
export const trackSubscriptionEvent = (plan: string, event: 'started' | 'completed' | 'cancelled') => {
  // Get price for the plan
  let price = 0;
  if (plan === 'monthly') {
    price = PRICING.monthly.price;
  } else if (plan === 'annual') {
    price = PRICING.annual.price;
  } else if (plan in PRICING.bundles) {
    price = PRICING.bundles[plan as keyof typeof PRICING.bundles].price;
  }

  // Google Analytics tracking (if available)
  if (typeof gtag !== 'undefined') {
    gtag('event', event === 'completed' ? 'purchase' : 'subscription_' + event, {
      transaction_id: `${plan}_${Date.now()}`,
      value: price,
      currency: 'USD',
      items: [{
        item_id: plan,
        item_name: plan === 'monthly' ? 'Pro Monthly' : plan === 'annual' ? 'Pro Annual' : `${plan} Bundle`,
        category: plan === 'monthly' || plan === 'annual' ? 'subscription' : 'bundle',
        quantity: 1,
        price: price
      }]
    });
  }
  
  // Console log for debugging
  console.log(`Subscription ${event}:`, plan, `$${price}`);
};
