#!/bin/bash

echo "🚨 EMERGENCY FIX: Add Domain to Firebase Auth"
echo "============================================="
echo ""
echo "You're getting this error:"
echo "'Add your domain (ancient-history-pwa.web.app) to OAuth redirect domains'"
echo ""
echo "🔧 IMMEDIATE SOLUTION:"
echo "1. The Firebase Console should have opened automatically"
echo "2. If not, go to: https://console.firebase.google.com/project/ancient-history-trivia/authentication/settings"
echo "3. Scroll down to 'Authorized domains' section"
echo "4. Click 'Add domain'"
echo "5. Enter: ancient-history-pwa.web.app"
echo "6. Click 'Add'"
echo ""
echo "✅ This will fix the authentication error immediately!"
echo ""
echo "🎯 AFTER FIXING:"
echo "1. Authentication will work on both domains"
echo "2. You can then figure out why you're accessing the wrong domain"
echo "3. Later, you can remove the unwanted domain once you switch to the correct one"
echo ""
echo "💡 WHY THIS IS HAPPENING:"
echo "- You're somehow accessing ancient-history-pwa.web.app instead of ancient-history-trivia.web.app"
echo "- This could be due to:"
echo "  • Browser bookmark pointing to wrong domain"
echo "  • Typing wrong URL"
echo "  • Redirect from somewhere"
echo "  • Cached DNS or browser data"
echo ""
echo "🚀 QUICK LINKS:"
echo "Firebase Console: https://console.firebase.google.com/project/ancient-history-trivia/authentication/settings"
echo "Correct App URL: https://ancient-history-trivia.web.app"
echo ""
echo "⚡ ADD THE DOMAIN NOW TO FIX THE ERROR!"
