name: GitHub Pages Deployment (DISABLED)

# This workflow is disabled - using Firebase Hosting only
# Firebase URL: https://ancient-history-trivia.web.app/

on:
  # Workflow disabled - only manual trigger available
  workflow_dispatch:
    inputs:
      confirm_deploy:
        description: 'Type "CONFIRM" to enable (not recommended)'
        required: true
        default: 'DISABLED'

jobs:
  disabled-notice:
    runs-on: ubuntu-latest
    steps:
      - name: Display Notice
        run: |
          echo "❌ GitHub Pages deployment is DISABLED"
          echo "✅ Using Firebase Hosting instead: https://ancient-history-trivia.web.app/"
          echo "This workflow has been intentionally disabled."
          if [ "${{ github.event.inputs.confirm_deploy }}" != "CONFIRM" ]; then
            echo "Exiting - deployment not confirmed"
            exit 1
          fi
