name: Security Audit

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  schedule:
    # Run security audit daily at 2 AM UTC
    - cron: '0 2 * * *'

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run security audit
        run: |
          echo "🔍 Running Yarn security audit..."
          
          # First, run a basic audit to see overall status
          echo "📊 Overall audit summary:"
          yarn audit || true
          
          echo ""
          echo "🎯 Checking specifically for high and critical vulnerabilities..."
          
          # Use yarn audit with specific level filtering
          # yarn audit --level high will exit with code 4 if moderate vulnerabilities exist
          # but we only care about high/critical, so we need to parse the output
          
          set +e  # Don't exit immediately on command failure
          
          # Run yarn audit for high/critical only and capture output
          yarn audit --level high > audit-high.txt 2>&1
          HIGH_EXIT_CODE=$?
          
          # Run yarn audit for critical only and capture output  
          yarn audit --level critical > audit-critical.txt 2>&1
          CRITICAL_EXIT_CODE=$?
          
          set -e  # Re-enable exit on error
          
          echo "High audit exit code: $HIGH_EXIT_CODE"
          echo "Critical audit exit code: $CRITICAL_EXIT_CODE"
          
          # Check if we have actual high or critical vulnerabilities
          if [ -f audit-high.txt ]; then
            HIGH_VULNS=$(grep -c "high" audit-high.txt || echo "0")
            echo "High vulnerabilities found: $HIGH_VULNS"
          else
            HIGH_VULNS=0
          fi
          
          if [ -f audit-critical.txt ]; then
            CRITICAL_VULNS=$(grep -c "critical" audit-critical.txt || echo "0")
            echo "Critical vulnerabilities found: $CRITICAL_VULNS"
          else
            CRITICAL_VULNS=0
          fi
          
          # Only fail if we have actual high or critical vulnerabilities
          if [ "$HIGH_VULNS" -eq 0 ] && [ "$CRITICAL_VULNS" -eq 0 ]; then
            echo "✅ No high or critical vulnerabilities detected!"
            echo "ℹ️  Build will continue (moderate/low vulnerabilities are acceptable)"
          else
            echo "❌ High or critical vulnerabilities found!"
            echo "📋 High severity audit results:"
            cat audit-high.txt || echo "No high audit results"
            echo ""
            echo "📋 Critical severity audit results:"
            cat audit-critical.txt || echo "No critical audit results"
            exit 1
          fi
          
          echo "🔒 Yarn security audit completed successfully"

      - name: Upload audit results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: yarn-security-audit-results
          path: |
            audit-high.txt
            audit-critical.txt
